schema {
  query: Query
}

type Query {
  page(id: String, name: PageNameInput): Page
  node(id: ID!): Node
  nodeByName(authority: String!, pageName: String!, name: String!): Node
}

input PageNameInput {
  # NOTE: authority is the complete hostname of the wiki (e.g. simple.wikipedia.org)
  authority: String!
  name: String!
}

type Page {
  id: ID!
  name: String!
  url: String!
  dateModified: String!
  hasPart(limit: Int, offset: Int): [Node]!
  # We had this as an associative array, (which GraphQL doesn't support); This
  # gets us close, but we should rethink.
  about: [Tuple!]!
}

type Node {
  id: ID!
  name: String!
  isPartOf: [ID!]!
  dateModified: String!
  unsafe: String!
}

type Tuple {
  key: String!
  val: String!
}
